services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "web"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"
    volumes:
      - ./db/data:/var/lib/mysql
